repos:
    - repo: local
      hooks:
          - id: isort
            name: isort
            stages: [commit]
            language: system
            entry: pipenv run isort
            types: [python]

          - id: black
            name: black
            stages: [commit]
            language: system
            entry: pipenv run black pydantic_quantlib tests
            types: [python]
